export * from './docsController.service';
import { DocsControllerService } from './docsController.service';
export * from './droitsController.service';
import { DroitsControllerService } from './droitsController.service';
export * from './groupUserController.service';
import { GroupUserControllerService } from './groupUserController.service';
export * from './homeResource.service';
import { HomeResourceService } from './homeResource.service';
export * from './loginController.service';
import { LoginControllerService } from './loginController.service';
export * from './typeDocsController.service';
import { TypeDocsControllerService } from './typeDocsController.service';
export * from './typeLiasseController.service';
import { TypeLiasseControllerService } from './typeLiasseController.service';
export * from './usersController.service';
import { UsersControllerService } from './usersController.service';
export * from './workFlowController.service';
import { WorkFlowControllerService } from './workFlowController.service';
export const APIS = [DocsControllerService, DroitsControllerService, GroupUserControllerService, HomeResourceService, LoginControllerService, TypeDocsControllerService, TypeLiasseControllerService, UsersControllerService, WorkFlowControllerService];
