export * from './docsController.service';
import { DocsControllerService } from './docsController.service';
export * from './liasseController.service';
import { LiasseControllerService } from './liasseController.service';
export * from './logPosteUserController.service';
import { LogPosteUserControllerService } from './logPosteUserController.service';
export * from './posteController.service';
import { PosteControllerService } from './posteController.service';
export * from './rolesController.service';
import { RolesControllerService } from './rolesController.service';
export * from './structureController.service';
import { StructureControllerService } from './structureController.service';
export * from './typeDocsController.service';
import { TypeDocsControllerService } from './typeDocsController.service';
export * from './typeLiasseController.service';
import { TypeLiasseControllerService } from './typeLiasseController.service';
export * from './usersController.service';
import { UsersControllerService } from './usersController.service';
export * from './workFlowController.service';
import { WorkFlowControllerService } from './workFlowController.service';
export const APIS = [DocsControllerService, LiasseControllerService, LogPosteUserControllerService, PosteControllerService, RolesControllerService, StructureControllerService, TypeDocsControllerService, TypeLiasseControllerService, UsersControllerService, WorkFlowControllerService];
