/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface AppUsers { 
    iduser?: string;
    name?: string;
    login?: string;
    typeprofil?: AppUsers.TypeprofilEnum;
    isactive?: boolean;
    dateCreation?: Date;
}
export namespace AppUsers {
    export type TypeprofilEnum = 'INTERN_ACTOR' | 'EXTERN_ACTOR';
    export const TypeprofilEnum = {
        INTERNACTOR: 'INTERN_ACTOR' as TypeprofilEnum,
        EXTERNACTOR: 'EXTERN_ACTOR' as TypeprofilEnum
    };
}