/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Liasses } from './liasses';
import { TypeDocs } from './typeDocs';

export interface Docs { 
    iddoc?: number;
    name?: string;
    extension?: string;
    description?: string;
    path?: string;
    cantset?: string;
    dateCreation?: Date;
    typedoc?: TypeDocs;
    liasse?: Liasses;
}