/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GroupUser } from './groupUser';
import { Profiles } from './profiles';

export interface GroupProfile { 
    idgroupprofile?: number;
    profileId?: Profiles;
    groupuserId?: GroupUser;
    isactive?: boolean;
    dateCreation?: Date;
    dateEnd?: Date;
}