/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Postes } from './postes';
import { Profiles } from './profiles';

export interface LogPosteUser { 
    idloguserposte?: number;
    dateDebut?: Date;
    dateFin?: Date;
    posteId?: Postes;
    ldaplogin?: Profiles;
}