/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface OrganigramSystem { 
    id?: number;
    name?: string;
    cssClass?: string;
    image?: string;
    title?: string;
    childs?: Array<OrganigramSystem>;
}