/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Structures } from './structures';

export interface Profiles { 
    name?: string;
    currentUser?: string;
    typeprofil?: Profiles.TypeprofilEnum;
    status?: boolean;
    structure?: Structures;
    dateCreation?: Date;
    idProfiles?: number;
}
export namespace Profiles {
    export type TypeprofilEnum = 'INTERN_ACTOR' | 'EXTERN_ACTOR';
    export const TypeprofilEnum = {
        INTERNACTOR: 'INTERN_ACTOR' as TypeprofilEnum,
        EXTERNACTOR: 'EXTERN_ACTOR' as TypeprofilEnum
    };
}