/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Profiles } from './profiles';
import { WorkFlow } from './workFlow';

export interface WorkFlowProfiles { 
    profilesId?: Profiles;
    workflowId?: WorkFlow;
    level?: number;
    isactive?: boolean;
    dateCreation?: Date;
    idworkflowposte?: number;
}